### ISSUE TITLE
Suboptimal zstd compression

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/filecoin-chain-archiver#55]
The [zstd compressor used here](https://github.com/filecoin-project/filecoin-chain-archiver/pull/50/files#diff-d2fc1fccf30dccd92e7738693e16f1fbc9959348a7f2f651e26fcdd1d8b50a6aR22) has unfortunate defaults / might not be the best compressor. It produces significantly larger files:

```
~$ curl -LI https://snapshots.mainnet.filops.net/minimal/latest.zst
content-length: 57102403792
content-disposition: attachment; filename="2382480_2022_11_30T04_00_00Z.car.zst"
```

vs the [original `zstd -T0 --long -15`](https://github.com/filecoin-project/filecoin-chain-archiver/issues/40#issuecomment-1205435788)
```
~$ curl -LI https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car.zst 
Content-Length: 37840040354
x-amz-website-redirect-location: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_2382481_2022-11-30_04-00-30.car.zst
```

cc @magik6k

**Comment by ribasushi** [comment]
@travisperson ping on this? Snapshots are still *way* larger than they could be.

**Comment by ognots** [comment]
We're using the maximum compression currently implemented in the zstd lib
